[local]
# Destination Dataverse
DESTINATION_DATAVERSE_API_KEY="secret" # Assumes you are using a single dataverse during local development
ODISSEI_API_KEY="@format {this.DESTINATION_DATAVERSE_API_KEY}"
SICADA_API_KEY="@format {this.DESTINATION_DATAVERSE_API_KEY}"

# Services
XML2JSON_API_TOKEN="local-dev-token"
HARVESTER_API_TOKEN="harvester-dev-apikey"

# MinIO Configuration
MINIO_SERVER_URL="http://minioS3:9002"
MINIO_KEY="minioadmin"
MINIO_SECRET="minioadmin"

[development]
# Data Sources
ODISSEI_API_KEY="secret"
SICADA_API_KEY="secret"

# Services
XML2JSON_API_TOKEN="secret"
MINTER_API_TOKEN="secret"
HARVESTER_API_TOKEN="secret"

# MinIO Configuration
MINIO_SERVER_URL="secret"
MINIO_KEY="secret"
MINIO_SECRET="secret"

[staging]
# Data Sources
ODISSEI_API_KEY="secret"
SICADA_API_KEY="secret"

# Services
XML2JSON_API_TOKEN="secret"
MINTER_API_TOKEN="secret"
HARVESTER_API_TOKEN="secret"

# MinIO Configuration
MINIO_SERVER_URL="secret"
MINIO_KEY="secret"
MINIO_SECRET="secret"

[production]
# Data Sources
ODISSEI_API_KEY="secret"
SICADA_API_KEY="secret"
HARVESTER_API_TOKEN="secret"

# Services
XML2JSON_API_TOKEN="secret"
MINTER_API_TOKEN="secret"

# MinIO Configuration
MINIO_SERVER_URL="secret"
MINIO_KEY="secret"
MINIO_SECRET="secret"
