[local]
# Destination Dataverse
DESTINATION_DATAVERSE_API_KEY="secret" # Assumes you are using a single dataverse during local development
ODISSEI_API_KEY="@format {this.DESTINATION_DATAVERSE_API_KEY}"
SICADA_API_KEY="@format {this.DESTINATION_DATAVERSE_API_KEY}"

# Services
XML2JSON_API_TOKEN="secret"
HARVESTER_API_TOKEN="harvester-dev-apikey"

# MinIO Configuration
MINIO_SERVER_URL="http://minioS3:9002"
AWS_ACCESS_KEY_ID="minioadmin"
AWS_SECRET_ACCESS_KEY="minioadmin"

[development]
# Data Sources
ODISSEI_API_KEY="secret"
SICADA_API_KEY="secret"

# Services
XML2JSON_API_TOKEN="secret"
MINTER_API_TOKEN="secret"
HARVESTER_API_TOKEN="secret"

# MinIO Configuration
MINIO_SERVER_URL="secret"
AWS_ACCESS_KEY_ID="secret"
AWS_SECRET_ACCESS_KEY="secret"

[staging]
# Data Sources
ODISSEI_API_KEY="secret"
SICADA_API_KEY="secret"

# Services
XML2JSON_API_TOKEN="secret"
MINTER_API_TOKEN="secret"
HARVESTER_API_TOKEN="secret"

# MinIO Configuration
MINIO_SERVER_URL="secret"
AWS_ACCESS_KEY_ID="secret"
AWS_SECRET_ACCESS_KEY="secret"

[production]
# Data Sources
ODISSEI_API_KEY="secret"
SICADA_API_KEY="secret"
HARVESTER_API_TOKEN="secret"

# Services
XML2JSON_API_TOKEN="secret"
MINTER_API_TOKEN="secret"

# MinIO Configuration
MINIO_SERVER_URL="secret"
AWS_ACCESS_KEY_ID="secret"
AWS_SECRET_ACCESS_KEY="secret"
