[local]
# Destination Dataverse
DESTINATION_DATAVERSE_API_KEY="secret" # Assumes you are using a single dataverse during local development
ODISSEI_API_KEY="@format {this.DESTINATION_DATAVERSE_API_KEY}"
SICADA_API_KEY="@format {this.DESTINATION_DATAVERSE_API_KEY}"

# Services
XML2JSON_API_TOKEN="local-dev-token"
HARVESTER_API_TOKEN="harvester-dev-apikey"

# S3 storage
S3_ENDPOINT_URL="http://minioS3:9002"
S3_ACCESS_KEY="minioadmin"
S3_SECRET_KEY="minioadmin"

[development]
# Data Sources
ODISSEI_API_KEY="secret"
SICADA_API_KEY="secret"

# Services
XML2JSON_API_TOKEN="secret"
MINTER_API_TOKEN="secret"
HARVESTER_API_TOKEN="secret"

# S3 storage
S3_ENDPOINT_URL="secret"
S3_ACCESS_KEY="secret"
S3_SECRET_KEY="secret"

[staging]
# Data Sources
ODISSEI_API_KEY="secret"
SICADA_API_KEY="secret"

# Services
XML2JSON_API_TOKEN="secret"
MINTER_API_TOKEN="secret"
HARVESTER_API_TOKEN="secret"

# S3 storage
S3_ENDPOINT_URL="secret"
S3_ACCESS_KEY="secret"
S3_SECRET_KEY="secret"

[production]
# Data Sources
ODISSEI_API_KEY="secret"
SICADA_API_KEY="secret"
HARVESTER_API_TOKEN="secret"

# Services
XML2JSON_API_TOKEN="secret"
MINTER_API_TOKEN="secret"

# S3 storage
S3_ENDPOINT_URL="secret"
S3_ACCESS_KEY="secret"
S3_SECRET_KEY="secret"
