[default]
ELSST_SKOSMOS_URL="https://thesauri.cessda.eu"
METADATA_PREFIX="oai_dc"
CID_METADATA_PREFIX="oai_datacite"
XSLT_TRANSFORMER_NAME="cid-oaipmh-to-dv-v1.xsl"
PREFECT_SLACK_WEBHOOK_BLOCK="slack-webhook-for-odissei-ingest"
MINT_DOIS = false
SEMANTIC_ENRICHMENT = false

[local]
debug = true
MINT_DOIS = false
DATAVERSE_MAPPER_URL="http://dataverse-mapper:8082"
DANS_TRANSFORMER_SERVICE="http://mts:1745"
EMAIL_SANITIZER_URL="http://email-sanitizer:7777/sanitize"
METADATA_REFINER_URL="http://metadata-refiner:7878"
METADATA_ENHANCER_URL="http://metadata-enhancer:7070"
HARVESTER_URL="http://oai-harvester:7890"

[development]
debug = false
MINT_DOIS = false
DATAVERSE_MAPPER_URL="https://dataverse-mapper.labs.dansdemo.nl"
DANS_TRANSFORMER_SERVICE="https://transformer.labs.dansdemo.nl"
EMAIL_SANITIZER_URL="https://sls-weur-dev-emailsanitizer-serverless.azurewebsites.net/api/sanitize"
METADATA_REFINER_URL="https://metadata-refiner.labs.dansdemo.nl"
METADATA_ENHANCER_URL="https://metadata-enhancer.labs.dansdemo.nl"
HARVESTER_URL="https://oai-harvester.labs.dansdemo.nl"

[staging]
debug = false
MINT_DOIS = false
DATAVERSE_MAPPER_URL="https://dataverse-mapper.labs.dansdemo.nl"
DANS_TRANSFORMER_SERVICE="https://transformer.labs.dansdemo.nl"
EMAIL_SANITIZER_URL="https://sls-weur-dev-emailsanitizer-serverless.azurewebsites.net/api/sanitize"
METADATA_REFINER_URL="https://metadata-refiner.labs.dansdemo.nl"
METADATA_ENHANCER_URL="https://metadata-enhancer.labs.dansdemo.nl"
HARVESTER_URL="https://oai-harvester.labs.dansdemo.nl"

[production]
debug = false
MINT_DOIS = true
SEMANTIC_ENRICHMENT = false
DOI_MINTER_URL = "https://dataciteminter.labs.dans.knaw.nl/submit-to-datacite/register"
DATAVERSE_MAPPER_URL="https://dataverse-mapper.labs.dansdemo.nl"
DANS_TRANSFORMER_SERVICE="https://transformer.labs.dansdemo.nl"
EMAIL_SANITIZER_URL="https://sls-weur-dev-emailsanitizer-serverless.azurewebsites.net/api/sanitize"
METADATA_REFINER_URL="https://metadata-refiner.labs.dansdemo.nl"
METADATA_ENHANCER_URL="https://metadata-enhancer.labs.dansdemo.nl"
HARVESTER_URL="https://oai-harvester.labs.dansdemo.nl"
