[default]
ELSST_SKOSMOS_URL="https://thesauri.cessda.eu"
METADATA_PREFIX="oai_dc"
CID_METADATA_PREFIX="oai_datacite"
XSLT_TRANSFORMER_NAME="cid-oaipmh-to-dv-v0.xsl"

[development]
debug = true
DOI_MINTER_URL = "http://datacite-minter:9999"
DATAVERSE_IMPORTER_URL="http://dataverse-importer:8989"
PUBLICATION_DATA_UPDATER_URL="http://publication-date-updater:8081"
METADATA_FETCHER_URL="http://metadata-fetcher:8092"
DATAVERSE_MAPPER_URL="http://dataverse-mapper:8082"
DANS_TRANSFORMER_SERVICE="https://transformer.labs.dansdemo.nl"
EMAIL_SANITIZER_URL="http://email-sanitizer:7777/sanitize"
METADATA_REFINER_URL="http://metadata-refiner:7878"
METADATA_ENHANCER_URL="http://metadata-enhancer:7070"
SEMANTIC_API_URL= "http://semanticapi:80/importdoi"
HARVESTER_URL="http://oai-harvester:7890"

[staging]
debug = false
DOI_MINTER_URL = "https://dataciteminter.labs.dans.knaw.nl/submit-to-datacite/register"
DATAVERSE_IMPORTER_URL="https://dataverse-importer.labs.dansdemo.nl"
PUBLICATION_DATA_UPDATER_URL="https://dataverse-date-updater.labs.dansdemo.nl"
METADATA_FETCHER_URL="https://dataverse-fetcher.labs.dansdemo.nl"
DATAVERSE_MAPPER_URL="https://dataverse-mapper.labs.dansdemo.nl"
DANS_TRANSFORMER_SERVICE="https://transformer.labs.dansdemo.nl"
EMAIL_SANITIZER_URL="https://sls-weur-dev-emailsanitizer-serverless.azurewebsites.net/api/sanitize"
METADATA_REFINER_URL="https://metadata-refiner.labs.dansdemo.nl"
METADATA_ENHANCER_URL="https://metadata-enhancer.labs.dansdemo.nl"
SEMANTIC_API_URL="http://semanticapi:80/importdoi"
HARVESTER_URL="https://oai-harvester.labs.dansdemo.nl"

[production]
debug = false
DOI_MINTER_URL = "https://dataciteminter.labs.dans.knaw.nl/submit-to-datacite/register"
DATAVERSE_IMPORTER_URL="https://dataverse-importer.labs.dansdemo.nl"
PUBLICATION_DATA_UPDATER_URL="https://dataverse-date-updater.labs.dansdemo.nl"
METADATA_FETCHER_URL="https://dataverse-fetcher.labs.dansdemo.nl"
DATAVERSE_MAPPER_URL="https://dataverse-mapper.labs.dansdemo.nl"
DANS_TRANSFORMER_SERVICE="https://transformer.labs.dansdemo.nl"
EMAIL_SANITIZER_URL="https://emailsanitizer.labs.dansdemo.nl/sanitize"
METADATA_REFINER_URL="https://metadata-refiner.labs.dansdemo.nl"
METADATA_ENHANCER_URL="https://metadata-enhancer.labs.dansdemo.nl"
SEMANTIC_API_URL="http://semanticapi:80/importdoi"
HARVESTER_URL="https://oai-harvester.labs.dansdemo.nl"
