services:
  prefect:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: 'prefect'
    volumes:
      - "/tmp:/tmp"
    ports:
      # Local development only
      - "4200:4200"
    env_file: .env
    depends_on:
      - db
    networks:
      - prefect
      - dataverse
      - ingest
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4200/api/health" ]
      interval: 15s
      timeout: 10s
      retries: 5

  prefect-worker:
    container_name: 'prefect-worker'
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file:
      - .env
      - .env.worker
    depends_on:
      prefect:
        condition: service_healthy
    networks:
      - prefect
      - dataverse
      - ingest

  db:
    image: postgres:latest
    container_name: db
    volumes:
      - prefectdb:/var/lib/postgresql/data
    env_file: .env
    networks:
      - prefect

networks:
  prefect:
  dataverse:
    name: dataverse_dataverse
    external: true
  ingest:
    external: true

volumes:
  prefectdb: