name: Docker Image CI

on:
  push:
    tags:
      - "*"

env:
  TAG: $GITHUB_REF_NAME
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  ORG: "odissei"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and push the Prefect server image
      - name: Build and push Prefect Server Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.server
          push: true
          tags: ${{ env.ORG }}/prefect:${{ github.ref_name }}

      # Build and push the Prefect worker image
      - name: Build and push Prefect Worker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.worker
          push: true
          tags: ${{ env.ORG }}/prefect-worker:${{ github.ref_name }}
